clientes/urls.py
from .views import PedidoClient, orcamento
from django.urls import path

app_name = 'cliente'

urlpatterns = [
    path('pedido/', PedidoClient, name='pedido-cliente'),
    path("orcamento/", orcamento, name="orcamento"),
]

project/urls.py
from django_hosts import patterns, host

host_patterns = patterns(
    '',
    host(r'bordado', 'project.bordado_urls', name='bordado'),
    host(r'adm', 'project.adm_urls', name='adm'),
)

urlpatterns = [
]

clientes/models.py
from django.db import models

# Create your models here.

clientes/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from empresa.models import Empresa, Pedido
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseBadRequest


@csrf_exempt
def PedidoClient(request, cod=None):
    if request.method == 'GET':
        codigo_ = request.GET.get('codigo').strip()
    elif cod:
        codigo_ = cod  # Evita erro se for None

    if not codigo_:
        # Retorna erro 400 se o código estiver vazio
        return HttpResponseBadRequest("Código inválido.")

    if codigo_.startswith('#'):
        codigo_ = codigo_[1:]

    # Garante que retorna 404 se não encontrar
    pedido = get_object_or_404(Pedido, codigo=codigo_)
    empresa = get_object_or_404(Empresa, pk=1)

    qr_pix = pedido.gerar_qr_pix()

    return render(request, 'clientes/pedido-cliente.html', {'pedido': pedido, 'dados': empresa, 'qr_pix': qr_pix})


def orcamento(request):
    if request.method == "POST":
        nome = request.POST.get("nome")
        email = request.POST.get("email")
        telefone = request.POST.get("telefone")
        mensagem = request.POST.get("mensagem")

        assunto = f"Solicitação de orçamento de {nome}"
        corpo = f"""
Nome: {nome}
Email: {email}
Telefone: {telefone}

Mensagem:
{mensagem}
        """

        send_mail(
            assunto,
            corpo,
            "micaelfarias.dev@gmail.com",  # Remetente
            ["contato@fariasfardas.com"],  # Destinatário
            fail_silently=False,
        )

        # Crie uma página de sucesso para redirecionamento
        return redirect("joycebordados:home")

    return render(request, "orcamento.html")  # Substitua pelo seu template

empresa/views/cliente_views.py
from django.shortcuts import render, redirect
from ..forms import ClienteForm
from ..models import Cliente
import locale
locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')

def ClientesListView(request):
    formcliente = ClienteForm()
    if request.method == "POST":
        formcliente = ClienteForm(request.POST)
        if formcliente.is_valid:
            formcliente.save()
    return render(request, 'empresa/clientes.html', {'formcliente':formcliente})

def EditCliente(request, pk):
    cliente = Cliente.objects.get(pk=pk)
    formcliente = ClienteForm(instance=cliente)
    
    if request.method == "POST":
        formcliente = ClienteForm(request.POST, instance=cliente)  # Atualiza a instância do cliente
        if formcliente.is_valid():  # Chama o método is_valid() corretamente
            formcliente.save()
            return redirect('adm:fechar_pagina')  # Redireciona após salvar
            
    return render(request, 'empresa/cliente-new.html', {'formcliente': formcliente})

clientes/templates/clientes/partial/login.html
<div class="blur-back back-log" >
  <div class="conteiner-buscar">
    <form action="{% url 'cliente:pedido-cliente' %}" method="get">
      <label for="codigo"><strong>Código do Pedido:</strong> <i>ex.:(#00000)</i></label>
      <input type="text" name="codigo" placeholder="Código" required />
      <div class="buttons">
          <button type="submit">Buscar</button>
          <button type="button" class="red" onclick="hiddenLog()">Fechar</button>
      </div>
  </form>
  </div>
</div>

clientes/templates/clientes/partial/pix.html
{% load static %}
<div class="blur-back back-pix" onclick="hiddenPix()">
    <div class="conteiner-pix">
        <img src="{{ pedido.qr_code.url }}" alt="QR Code">
        <textarea name="pix" id="pix" readonly>{{ qr_pix }}</textarea>
        <button onclick="copiarTexto()">Copiar código</button>
        <div style="text-align: center;">
            <p>Após o pagamento, </p><p>Enviar o comprovante para </p>
                <a target="_blank" class="link-zap" href="https://wa.me/5586988589902?text=Comprovante%20de%20pagamento%20do%20*pedido%20%23{{ pedido.codigo }}*">Whatsapp da Empresa</a>
            </p>
        </div>
    </div>
  </div>
  
  <script src="{% static 'global/js/pix.js' %}"></script>