clientes/urls.py
from .views import PedidoClient, orcamento
from django.urls import path

app_name = 'cliente'

urlpatterns = [
    path('pedido/', PedidoClient, name='pedido-cliente'),
    path("orcamento/", orcamento, name="orcamento"),
]

project/urls.py
from django_hosts import patterns, host

host_patterns = patterns(
    '',
    host(r'bordado', 'project.bordado_urls', name='bordado'),
    host(r'adm', 'project.adm_urls', name='adm'),
)

urlpatterns = [
]

clientes/models.py
from django.db import models

# Create your models here.

empresa/models.py
from django.utils.timezone import now
from django.contrib.auth.models import User
import os
from django.dispatch import receiver
from django.db.models.signals import post_delete, post_save
from django.db import models
import qrcode
from pixqrcode import GenerateCode, Pix, PixQrCode
from django.core.files.base import ContentFile
from io import BytesIO


def rename_logo(instance, filename):
    """ Renomeia a imagem para sempre ser 'logo.png' na pasta 'logo/' """
    return os.path.join('logo/', 'logo.png')


class Empresa(models.Model):
    nome = models.CharField(max_length=100)
    logo = models.ImageField(upload_to=rename_logo, null=True, blank=True)
    sobre = models.TextField()
    foto_sobre = models.ImageField(
        upload_to='foto_sobre', null=True, blank=True)
    email = models.EmailField(max_length=100)
    telefone = models.CharField(max_length=15)
    endereco = models.CharField(max_length=100)
    numero = models.CharField(max_length=100)
    bairro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=2)
    cep = models.CharField(max_length=9)

    def __str__(self):
        return self.nome

    def save(self, *args, **kwargs):
        if Empresa.objects.exists() and not self.pk:
            raise ValueError("Só pode existir uma empresa no banco de dados!")
        if self.pk:  # Se já existe um objeto salvo
            empresa_antiga = Empresa.objects.get(pk=self.pk)
            if empresa_antiga.logo and self.logo != empresa_antiga.logo:
                if os.path.isfile(empresa_antiga.logo.path):
                    os.remove(empresa_antiga.logo.path)
            if empresa_antiga.foto_sobre and self.foto_sobre != empresa_antiga.foto_sobre:
                if os.path.isfile(empresa_antiga.foto_sobre.path):
                    os.remove(empresa_antiga.foto_sobre.path)
        super().save(*args, **kwargs)


class FotosCarrossel(models.Model):
    empresa = models.ForeignKey(
        Empresa, on_delete=models.CASCADE, related_name="fotos_carrossel")
    foto = models.ImageField(upload_to='fotos_carrossel')

    def __str__(self):
        return self.empresa.nome


@receiver(post_delete, sender=FotosCarrossel)
def delete_foto_carrossel(sender, instance, **kwargs):
    # Deleta a foto do carrossel se existir
    if instance.foto:
        if os.path.isfile(instance.foto.path):
            os.remove(instance.foto.path)


class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    numero = models.CharField(max_length=16)

    def save(self, *args, **kwargs):
        newnumber = ''
        for n in self.numero:
            if n.isnumeric():
                newnumber += n

        self.numero = newnumber

        return super().save(*args, **kwargs)

    def __str__(self):
        return self.nome


class Pedido(models.Model):
    codigo = models.CharField(
        max_length=5, unique=True, blank=True, null=True)
    cliente = models.ForeignKey(
        Cliente, on_delete=models.CASCADE, null=True, blank=True)
    empresa = models.ForeignKey(
        Empresa, on_delete=models.CASCADE, null=True, blank=True)
    data = models.DateTimeField(auto_now_add=True)
    data_update = models.DateTimeField(auto_now=True)
    data_entrega = models.DateField(blank=True, null=True)
    produto = models.CharField(max_length=100)
    quantidade = models.IntegerField(null=True, blank=True)
    valor = models.DecimalField(
        max_digits=99, decimal_places=2, null=True, blank=True)
    valor_total = models.DecimalField(
        max_digits=99, decimal_places=2, blank=True, null=True)
    observacao = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=100, choices=(
        ('0-pendente', 'Pendente'),
        ('1-producao', 'Produção'),
        ('2-pronto', 'Pronto para entrega'),
        ('3-entregue', 'Finalizado')), blank=True, null=True, default='0-pendente',
    )
    pago = models.BooleanField(default=False)
    qr_code = models.ImageField(upload_to='qr_codes/', blank=True, null=True)

    def gerar_codigo_unico(self):
        import random
        import string
        """Gera um código único para o pedido"""
        while True:
            codigo = random.choices(
                string.ascii_uppercase + string.digits, k=4)
            codigo.append(str(random.randint(0, 9)))
            codigo = ''.join(codigo)
            if not Pedido.objects.filter(codigo=codigo).exists():
                return codigo

    def gerar_qr_pix(self):
        nome = 'Jocileide Fernanda da Silva Farias'
        numero = '86988589907'
        valor = str(int(self.valor_total*100))
        pix = f'({numero[:2]}) {numero[2:]}'
        pix = PixQrCode(nome, pix, "SAO PAULO",
                        valor).generate_code()

        # Gerar o QR Code
        qr = qrcode.make(pix)
        buffer = BytesIO()
        qr.save(buffer, format="PNG")

        # Salvar o QR Code no banco de dados como imagem
        self.qr_code.save(f'qr_{self.codigo}.png',
                          ContentFile(buffer.getvalue()), save=False)

        return pix

    def save(self, *args, **kwargs):
        if self.valor is None:
            self.valor = 0
        if self.quantidade is None:
            self.quantidade = 0
        if self.codigo is '':
            self.codigo = self.gerar_codigo_unico()
        if self.valor is not None and self.quantidade is not None:

            self.valor_total = self.valor * self.quantidade
        else:
            self.valor_total = 0

        return super().save(*args, **kwargs)

    def __str__(self):
        return self.codigo


class HistoricoPedido(models.Model):
    pedido = models.ForeignKey(
        Pedido, on_delete=models.CASCADE, related_name="historico")
    alteracoes = models.JSONField()  # Guarda as mudanças feitas
    data_alteracao = models.DateTimeField(default=now)

clientes/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from empresa.models import Empresa, Pedido
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseBadRequest


@csrf_exempt
def PedidoClient(request, cod=None):
    if request.method == 'GET':
        codigo_ = request.GET.get('codigo').strip()
    elif cod:
        codigo_ = cod  # Evita erro se for None

    if not codigo_:
        # Retorna erro 400 se o código estiver vazio
        return HttpResponseBadRequest("Código inválido.")

    if codigo_.startswith('#'):
        codigo_ = codigo_[1:]

    # Garante que retorna 404 se não encontrar
    pedido = get_object_or_404(Pedido, codigo=codigo_)
    empresa = get_object_or_404(Empresa, pk=1)

    qr_pix = pedido.gerar_qr_pix()

    return render(request, 'clientes/pedido-cliente.html', {'pedido': pedido, 'dados': empresa, 'qr_pix': qr_pix})


def orcamento(request):
    if request.method == "POST":
        nome = request.POST.get("nome")
        email = request.POST.get("email")
        telefone = request.POST.get("telefone")
        mensagem = request.POST.get("mensagem")

        assunto = f"Solicitação de orçamento de {nome}"
        corpo = f"""
Nome: {nome}
Email: {email}
Telefone: {telefone}

Mensagem:
{mensagem}
        """

        send_mail(
            assunto,
            corpo,
            "micaelfarias.dev@gmail.com",  # Remetente
            ["contato@fariasfardas.com"],  # Destinatário
            fail_silently=False,
        )

        # Crie uma página de sucesso para redirecionamento
        return redirect("joycebordados:home")

    return render(request, "orcamento.html")  # Substitua pelo seu template

empresa/views/carrossel_views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, redirect, get_object_or_404
from ..models import Empresa, FotosCarrossel
from ..forms import FotosCarrosselForm
import locale
locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')


def CarrosselProfileView(request):
    dados = Empresa.objects.get(pk=1)
    fotos = dados.fotos_carrossel.all()
    form = FotosCarrosselForm(initial={'empresa': dados})
    return render(request, 'empresa/profile-carrosel.html', {'dados': dados, 'form': form, 'fotos': fotos})


def DelFotoCarroselView(request, pk):
    foto = get_object_or_404(FotosCarrossel, pk=pk)
    foto.delete()
    return redirect('adm:carrossel')



def AddFotoCarroselView(request):
    if request.method == "POST":
        form = FotosCarrosselForm(request.POST or None,
                                  request.FILES or None,)
        if form.is_valid():
            form.save()
            print('salvo')
            return redirect('adm:carrossel')
        else:
            print(form.errors) 
            return redirect('adm:carrossel')
    return redirect('adm:carrossel')

empresa/views/cliente_views.py
from django.shortcuts import render, redirect
from ..forms import ClienteForm
from ..models import Cliente
import locale
locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')

def ClientesListView(request):
    formcliente = ClienteForm()
    if request.method == "POST":
        formcliente = ClienteForm(request.POST)
        if formcliente.is_valid:
            formcliente.save()
    return render(request, 'empresa/clientes.html', {'formcliente':formcliente})

def EditCliente(request, pk):
    cliente = Cliente.objects.get(pk=pk)
    formcliente = ClienteForm(instance=cliente)
    
    if request.method == "POST":
        formcliente = ClienteForm(request.POST, instance=cliente)  # Atualiza a instância do cliente
        if formcliente.is_valid():  # Chama o método is_valid() corretamente
            formcliente.save()
            return redirect('adm:fechar_pagina')  # Redireciona após salvar
            
    return render(request, 'empresa/cliente-new.html', {'formcliente': formcliente})

empresa/views/dados_views.py
from django.shortcuts import render, redirect, get_object_or_404
from ..models import Empresa
from ..forms import EmpresaForm
import locale
locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')


def DadosProfileView(request):
    dados = Empresa.objects.get(pk=1)
    form = EmpresaForm(instance=dados)
    return render(request, 'empresa/profile-dados.html', {'dados': dados, 'form': form})

def DadosEditView(request):
    dados = get_object_or_404(Empresa, pk=1)
    if request.method == "POST":
        form = EmpresaForm(request.POST or None,
                           request.FILES or None, instance=dados)
        if form.is_valid():
            form.save()
            return redirect('adm:dados')
        else:
            return redirect('adm:dados')
    return redirect('adm:dados')

empresa/views/dash_views.py
from django.shortcuts import render
from django.utils.timezone import now
from ..models import Empresa
from ..forms import FilterForm
from datetime import datetime
from dateutil.relativedelta import relativedelta
import locale
locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')


def DashBoardView(request):
    dados = Empresa.objects.get(pk=1)
    filter = {
        'data_init': request.GET.get('data_init') or (datetime(now().year, now().month, 1)).strftime('%Y-%m-%d'),
        'data_end': request.GET.get('data_end') or (datetime.now()).strftime('%Y-%m-%d')
    }
    if isinstance(filter['data_init'], str):
        filter['data_init'] = datetime.strptime(
            filter['data_init'], '%Y-%m-%d')
    if isinstance(filter['data_end'], str):
        filter['data_end'] = datetime.strptime(filter['data_end'], '%Y-%m-%d')
    dif_days = filter['data_end'] - filter['data_init']
    filtercompare = {
        'data_init': (filter['data_init'] - relativedelta(months=1)),
        'data_end': (filter['data_init'] - relativedelta(months=1) + dif_days)
    }
    if filtercompare['data_end'] > filter['data_init']:
        filtercompare['data_end'] = (
            filter['data_init'] - relativedelta(days=1))

    filter['data_init'] = filter['data_init'].strftime('%Y-%m-%d')
    filter['data_end'] = filter['data_end'].strftime('%Y-%m-%d')
    filtercompare['data_init'] = filtercompare['data_init'].strftime(
        '%Y-%m-%d')
    filtercompare['data_end'] = filtercompare['data_end'].strftime('%Y-%m-%d')

    contexto = {'dados': dados, 'filter': filter}
    form = FilterForm(initial=filter)
    form2 = FilterForm(initial=filtercompare)
    contexto.update({'form': form, 'form2': form2})
    return render(request, 'empresa/profile-detail.html', context=contexto)

empresa/views/global_views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from ..forms import CustomLoginForm
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from ..models import Empresa, Pedido
from ..utils import Json_Grafico, enviar_msg, Json_Pedido
import locale
locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')

def fechar_pagina(request):
    return render(request, 'global/fechar.html')

def Login(request):
    if request.user.is_authenticated:
        return redirect('adm:empresa')
    dados = Empresa.objects.get(pk=1)
    if request.method == 'POST':
        form = CustomLoginForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('adm:empresa')
            else:
                form.add_error(None, 'Usuário ou senha inválidos')
        else:
            form.add_error(None, 'Erro no formulário de login')
    else:
        form = CustomLoginForm()

    return render(request, 'empresa/profile-login.html', {'form': form, 'dados': dados})

def grafico_json(request):
    data = Json_Grafico()
    return JsonResponse(data, safe=False)

def pedidos_json(request):
    data = Json_Pedido()
    return JsonResponse(data, safe=False)


def whastapp(request, pk):
    pedido = Pedido.objects.get(pk=pk)
    num = pedido.cliente.numero
    dado = dict()
    dado.update(enviar_msg(num, pedido))
    return render(request, 'global/whats.html', dado)

empresa/views/pedidos_views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from ..models import Empresa, Pedido
from ..forms import PedidosForm, ProcurarForm, ClienteForm
import locale
locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')


def PedidosListView(request):
    pesquisa = request.GET.get('q', '').strip()
    pg = request.GET.get('pago', '').strip()
    status = request.GET.get('status', '').strip()
    filtro_q = Q()
    filtro_pg = Q()
    filtro_est = Q()
    if pesquisa:
        filtro_q = Q(codigo__icontains=pesquisa) | Q(
            cliente__nome__icontains=pesquisa)
    if pg in ["True", "False"]:  
        filtro_pg = Q(pago=(pg))
    if status:
        filtro_est = Q(status=status)
    dados = Empresa.objects.get(pk=1)
    pedidos = Pedido.objects.filter(
        filtro_q & filtro_pg & filtro_est).order_by('status', '-id')
    form = ProcurarForm(request.GET or None)
    return render(request, 'empresa/profile-pedidos.html', {'form': form, 'dados': dados, 'pedidos': pedidos, })

def PedidodetailView(request, pk):
    dados = Empresa.objects.get(pk=1)
    pedido = Pedido.objects.get(pk=pk)
    form = PedidosForm(instance=pedido)
    return render(request, 'empresa/pedido-detail.html', {'dados': dados, 'pedido': pedido, 'form': form, })

def PedidoEditView(request, pk):
    pedido = get_object_or_404(Pedido, pk=pk)
    if request.method == "POST":
        form = PedidosForm(request.POST or None, instance=pedido)
        if form.is_valid():
            form.save()
            return redirect('adm:fechar_pagina')
        else:
            print(form.errors)  
            return redirect('adm:pedidos')
    return redirect('adm:pedidos')


def PedidoDelView(request, pk):
    pedido = get_object_or_404(Pedido, pk=pk)
    if request.method == "POST":
        pedido.delete()
        return redirect('adm:fechar_pagina')
    return redirect('adm:pedidos')


def PedidoNewView(request):
    dados = Empresa.objects.get(pk=1)
    form = PedidosForm()
    formcliente = ClienteForm()
    if request.method == 'POST':
        formcliente = ClienteForm(request.POST)
        if formcliente.is_valid():  
            formcliente.save()
    return render(request, 'empresa/pedido-new.html', {'dados': dados, 'form': form, 'formcliente':formcliente})


def PedidoNewSaveView(request):
    form = PedidosForm()
    if request.method == "POST":
        if request.method == 'POST':
            form = PedidosForm(request.POST)
            if form.is_valid():  
                pedido = form.save(commit=False)
                pedido.save()
                return redirect('adm:fechar_pagina')
            else:
                return render(request, 'empresa/pedido-new.html', {'form': form})

empresa/templates/empresa/cliente-edit.html
{% extends 'global/base-admin.html' %} 
{% block titulo %} Pedido | Edit {% endblock %} 
{% block main %} {% load filtros %}
<div class="divmeddia">
  {% include "empresa/partial/clientenovo.html" %}
</div>

{% endblock %}

empresa/templates/empresa/clientes.html
{% extends 'global/base-admin.html' %} 
{% load static %} {% load filtros %} 
{% block titulo %} Clientes
{% endblock %} {% block main %} {% include "empresa/partial/clientes.html" %} 
{% endblock %} 
{% block script %}
<script src="{% static "global/js/clientes.js" %}"></script>
{% endblock script %}

empresa/templates/empresa/pedido-detail.html
{% extends 'global/base-admin.html' %}
{% block titulo %}
  Pedido #{{ pedido.codigo }} | Edit
{% endblock %}
{% block main %}
  {% load filtros %}
  <div class="divmeddia">
    <div class="pedido-detail-conteiner">
      <form method="post" action="{% url 'adm:pedido-edit' pk=pedido.pk %}" style='justify-items: center;'>
      <div class="cliente">
        <h2>Cliente</h2>

        <div class="dados">
          <span>
            <strong>Nome:</strong></span> {{ form.cliente }}
          
          <p>
            <strong>Telefone:</strong> {{ pedido.cliente.numero|formatar_telefone }}
          </p>
        </div>
      </div>
      <hr />
      <div class="pedido">
        {% csrf_token %}
        <h2>Pedido</h2><p class="cod-pedido">
          <strong>#{{ pedido.codigo }}</strong>
          <span style="display: none;">{{ form.codigo }}</span>
          <span style="display: none;">{{ form.empresa }}</span>
          <span style="display: none;">{{ form.data_entrega }}</span>
        </p>
        <p>
          <strong>Data de Entrega:</strong>
          {{ pedido.data_entrega|date:'d/m/Y' }}
        </p>
        <p>
          <strong>{{ form.produto }}</strong>
        </p>
        <p>
          <strong>Descrição:</strong>
        </p>
        {{ form.observacao }}
        <p>
          <strong>Status:</strong>
          <strong class="dot active {% if pedido.status.0 == '1' %}
              
              
            
              red




            {% elif pedido.status.0 == '2' %}
              
              
            
              gren




            {% elif pedido.status.0 == '3' %}
              
              
            
              gray




            {% endif %}">

          </strong>

          {{ form.status }}
        </p>
        <div class="valores">
          <span>
            <strong>Quantidade:</strong>
            {{ form.quantidade }}
          </span>

          <span>
            <strong>Valor:</strong>
            {{ form.valor }}
          </span>

          <span>
            <strong>Valor Total:</strong>
            <p class="valortot">{{ pedido.valor_total|monetario }}</p>
          </span>
          <span>
            <strong>Pago:</strong>
            {{ form.pago }}
          </span>
        </div>
        <button type="submit">Editar</button>
      </div>
    </form>
    <form action="{% url "adm:pedido-del" pedido.pk %}" method="post" style='justify-items: center;'>
      {% csrf_token %}
        <div class='pedido'>
          <button type="submit" class='red'>Deletar</button>
        </div>
    </form>
  </div>
</div>
  <script>

    document.getElementsByTagName('form')[0].addEventListener('submit', function(event) {
      event.preventDefault()
      Swal.fire({
        title: "Tem certeza?",
        text: "Deseja editar o pedido #{{ pedido.codigo }}?.",
        icon: "question",
        showCancelButton: true,
        confirmButtonText: "Sim",
        cancelButtonText: "Não"
    }).then((result) => {
        if (result.isConfirmed) {
          Swal.fire({
            title: "Pedido editado",
            icon: "success",
            showCancelButton: false,
            confirmButtonText: "ok"
          }).then((result) => {
            this.submit()
      })
        }
    });
  });
    document.getElementsByTagName('form')[1].addEventListener('submit', function(event) {
      event.preventDefault()
      Swal.fire({
        title: "Tem certeza?",
        text: "Deseja excluir o pedido #{{ pedido.codigo }}?.",
        icon: "warning",
        showCancelButton: true,
        confirmButtonText: "Sim",
        cancelButtonText: "Não"
    }).then((result) => {
        if (result.isConfirmed) {
          Swal.fire({
            title: "Pedido excluir",
            icon: "success",
            showCancelButton: false,
            confirmButtonText: "ok"
          }).then((result) => {
            this.submit()
      })
        }
    });
  });

  document.addEventListener("DOMContentLoaded", function() {
    let dataInput = document.querySelector("#id_data_entrega");
    dataInput.value = "{{ pedido.data_entrega|date:'Y-m-d' }}";
});

document.querySelector("input#id_valor").addEventListener("input", function (e) {
  let value = e.target.value.replace(/[^\d,]/g, ''); // Remove tudo, exceto números e vírgulas
  
  // Se houver mais de 2 dígitos, coloca a vírgula nas últimas duas casas
  if (value.length > 2) {
    value = `${value.slice(0, -2)}.${value.slice(-2)}`;  // Coloca vírgula entre os números
  }
  
  e.target.value = value;
});
function ToRealBrasil(valor){
  return valor.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })
}

var inputvalor = document.querySelector('#id_valor')
var valortotal = document.querySelector("span .valortot")
var quantidade = document.querySelector("#id_quantidade")

quantidade.addEventListener("input", function (e) {
  let valoratualal = e.target.value * inputvalor.value

  valortotal.innerHTML = ToRealBrasil(valoratualal)

})
inputvalor.addEventListener("input", function (e) {
  let valoratualal = e.target.value * quantidade.value

  valortotal.innerHTML = ToRealBrasil(valoratualal)

})



  </script>
{% endblock %}

empresa/templates/empresa/pedido-new.html
{% extends 'global/base-admin.html' %}
{% block titulo %}
  Pedido | New
{% endblock %}
{% block main %}
  {% load filtros %}
  <div class="divmeddia">
    <form method="post" action="{% url "adm:save-pedido" %}">
      {% csrf_token %}
      <div class="pedido-detail-conteiner">
        <div class="cliente">
          <h2>Cliente</h2>
          <div>
            {{ form.cliente }}
            <a href="#" class="button-style add-related"><i class="fa-solid fa-user-plus"></i></a>
          </div>
        </div>
        <hr />
        <div class="pedido">
          <span style="display:none;">{{ form.empresa }}</span>
          <span style="display:none;">{{ form.codigo }}</span>
          <h2>Pedido</h2>
          {% if form.errors %}
              <ul class="error-list">
                {% for error in form.errors %}
                  <li class="error">{{ form.errors }}</li>
                {% endfor %}
              </ul>
            {% endif %}
          {{ form.data_entrega.label_tag }}
          {{ form.data_entrega }}
          {{ form.produto.label_tag }}
          {{ form.produto }}
          {{ form.observacao.label_tag }}
          {{ form.observacao }}
          {{ form.status.label_tag }}
          {{ form.status }}
          <div class="valores">
            <span>
              {{ form.quantidade.label_tag }}
              {{ form.quantidade }}
            </span>
            <span>
              {{ form.valor.label_tag }}
              {{ form.valor }}
            </span>
            <span style="display:none;">
              {{ form.valor_total }}
            </span>
            <span>
              {{ form.pago.label_tag }}
              {{ form.pago }}
            </span>
          </div>
          <button type="submit">Salvar</button>
        </div>
      </div>
    </form>
  </div>

<div class="pop-new-cliente">
  {% include "empresa/partial/clientenovo.html" %}
</div>


  <script>
// Seleciona o botão que abre o popup
var add = document.querySelector('.add-related');
var cancel = document.querySelector("body > main > div.pop-new-cliente > div > form > a > button");
var popcliente = document.querySelector('.pop-new-cliente');

add.addEventListener('click', function (event) {
    event.preventDefault();
    popcliente.style.top = '100px'
    //popcliente.classList.add('show')
});
cancel.addEventListener('click', function (event) {
    event.preventDefault();
    popcliente.style.top = '-500px'

});

// Manipula o envio do formulário na página principal
var form = document.querySelector('form');
if (form) {
  form.addEventListener('submit', function (event) {
    event.preventDefault()
    Swal.fire({
      title: "Tem certeza?",
      text: "Deseja Criar um pedido?.",
      icon: "question",
      showCancelButton: true,
      confirmButtonText: "Sim",
      cancelButtonText: "Não"
    }).then((result) => {
      if (result.isConfirmed) {
        Swal.fire({
          title: "Pedido criado",
          icon: "success",
          showCancelButton: false,
          confirmButtonText: "ok"
        }).then((result) => {
          this.submit()
        })
      }
    });
  });
}



var inputvalor = document.querySelector('#id_valor')
document.querySelector("input#id_valor").addEventListener("input", function (e) {
  let value = e.target.value.replace(/[^\d,]/g, ''); // Remove tudo, exceto números e vírgulas

  // Se houver mais de 2 dígitos, coloca a vírgula nas últimas duas casas
  if (value.length > 2) {
    value = `${value.slice(0, -2)}.${value.slice(-2)}`;  // Coloca vírgula entre os números
  }

  e.target.value = value;
});

</script>
{% endblock %}

empresa/templates/empresa/pedido-profile.html
{% extends 'global/base.html' %} {% load static %} {% load filtros %}
{% block titulo %}
  {{ dados.nome }}
{% endblock %} {% block main %}
{% include "empresa/partial/pedidos.html" %}
{% endblock %}
{% block script %}
{% include "empresa/js.html" %}


{% endblock %}

empresa/templates/empresa/profile-carrosel.html
{% extends 'global/base-admin.html' %} {% load static %} {% load filtros %}
{% block titulo %}
Fotos Carrossel
{% endblock %} {% block main %}
{% include "empresa/partial/carrossel.html" %}
{% endblock %}
{% block script %}



{% endblock %}

empresa/templates/empresa/profile-dados.html
{% extends 'global/base-admin.html' %} 
{% load static %} 
{% load filtros %} 
{% block titulo %} Configuração {% endblock %} 
{% block main %} 
{% include "empresa/partial/dados.html" %}
{% endblock %}

empresa/templates/empresa/profile-detail.html
{% extends 'global/base-admin.html' %} {% load static %} {% load filtros %}
{% block titulo %}
  {{ dados.nome }}
{% endblock %} {% block main %}
    {% include "global/partial/load.html" %}
    {% include "empresa/partial/dash.html" %}
{% endblock %}
{% block script %}
<script src="{% static "global/js/dash.js" %}"></script>
{% endblock %}

empresa/templates/empresa/profile-login.html
{% extends 'global/base-admin.html' %} 
{% load static %} 
{% load filtros %} 
{% block titulo %} Login {% endblock %} 
{% block main %} 
    {% include "global/partial/load.html" %}
    {% include "empresa/partial/login.html" %} 
{% endblock %} 