clientes/urls.py
from .views import PedidoClient, orcamento
from django.urls import path

app_name = 'cliente'

urlpatterns = [
    path('pedido/', PedidoClient, name='pedido-cliente'),
    path("orcamento/", orcamento, name="orcamento"),
]

joycebordados/urls.py
from django.urls import path
from .views import HomeView, red

app_name = 'joycebordados'

urlpatterns = [
    path('', HomeView, name='home'),
    path('<str:cod>', red, name='red'),
]

project/urls.py
from django_hosts import patterns, host

host_patterns = patterns(
    '',
    host(r'bordado', 'project.bordado_urls', name='bordado'),
    host(r'adm', 'project.adm_urls', name='adm'),
)

urlpatterns = [
]

empresa/models.py
from django.utils.timezone import now
from django.contrib.auth.models import User
import os
from django.dispatch import receiver
from django.db.models.signals import post_delete, post_save
from django.db import models
import qrcode
from pixqrcode import GenerateCode, Pix, PixQrCode
from django.core.files.base import ContentFile
from io import BytesIO


def rename_logo(instance, filename):
    """ Renomeia a imagem para sempre ser 'logo.png' na pasta 'logo/' """
    return os.path.join('logo/', 'logo.png')


class Empresa(models.Model):
    nome = models.CharField(max_length=100)
    logo = models.ImageField(upload_to=rename_logo, null=True, blank=True)
    sobre = models.TextField()
    foto_sobre = models.ImageField(
        upload_to='foto_sobre', null=True, blank=True)
    email = models.EmailField(max_length=100)
    telefone = models.CharField(max_length=15)
    endereco = models.CharField(max_length=100)
    numero = models.CharField(max_length=100)
    bairro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=2)
    cep = models.CharField(max_length=9)

    def __str__(self):
        return self.nome

    def save(self, *args, **kwargs):
        if Empresa.objects.exists() and not self.pk:
            raise ValueError("Só pode existir uma empresa no banco de dados!")
        if self.pk:  # Se já existe um objeto salvo
            empresa_antiga = Empresa.objects.get(pk=self.pk)
            if empresa_antiga.logo and self.logo != empresa_antiga.logo:
                if os.path.isfile(empresa_antiga.logo.path):
                    os.remove(empresa_antiga.logo.path)
            if empresa_antiga.foto_sobre and self.foto_sobre != empresa_antiga.foto_sobre:
                if os.path.isfile(empresa_antiga.foto_sobre.path):
                    os.remove(empresa_antiga.foto_sobre.path)
        super().save(*args, **kwargs)


class FotosCarrossel(models.Model):
    empresa = models.ForeignKey(
        Empresa, on_delete=models.CASCADE, related_name="fotos_carrossel")
    foto = models.ImageField(upload_to='fotos_carrossel')

    def __str__(self):
        return self.empresa.nome


@receiver(post_delete, sender=FotosCarrossel)
def delete_foto_carrossel(sender, instance, **kwargs):
    # Deleta a foto do carrossel se existir
    if instance.foto:
        if os.path.isfile(instance.foto.path):
            os.remove(instance.foto.path)


class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    numero = models.CharField(max_length=16)

    def save(self, *args, **kwargs):
        newnumber = ''
        for n in self.numero:
            if n.isnumeric():
                newnumber += n

        self.numero = newnumber

        return super().save(*args, **kwargs)

    def __str__(self):
        return self.nome


class Pedido(models.Model):
    codigo = models.CharField(
        max_length=5, unique=True, blank=True, null=True)
    cliente = models.ForeignKey(
        Cliente, on_delete=models.CASCADE, null=True, blank=True)
    empresa = models.ForeignKey(
        Empresa, on_delete=models.CASCADE, null=True, blank=True)
    data = models.DateTimeField(auto_now_add=True)
    data_update = models.DateTimeField(auto_now=True)
    data_entrega = models.DateField(blank=True, null=True)
    produto = models.CharField(max_length=100)
    quantidade = models.IntegerField(null=True, blank=True)
    valor = models.DecimalField(
        max_digits=99, decimal_places=2, null=True, blank=True)
    valor_total = models.DecimalField(
        max_digits=99, decimal_places=2, blank=True, null=True)
    observacao = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=100, choices=(
        ('0-pendente', 'Pendente'),
        ('1-producao', 'Produção'),
        ('2-pronto', 'Pronto para entrega'),
        ('3-entregue', 'Finalizado')), blank=True, null=True, default='0-pendente',
    )
    pago = models.BooleanField(default=False)
    qr_code = models.ImageField(upload_to='qr_codes/', blank=True, null=True)

    def gerar_codigo_unico(self):
        import random
        import string
        """Gera um código único para o pedido"""
        while True:
            codigo = random.choices(
                string.ascii_uppercase + string.digits, k=4)
            codigo.append(str(random.randint(0, 9)))
            codigo = ''.join(codigo)
            if not Pedido.objects.filter(codigo=codigo).exists():
                return codigo

    def gerar_qr_pix(self):
        nome = 'Jocileide Fernanda da Silva Farias'
        numero = '86988589907'
        valor = str(int(self.valor_total*100))
        pix = f'({numero[:2]}) {numero[2:]}'
        pix = PixQrCode(nome, pix, "SAO PAULO",
                        valor).generate_code()

        # Gerar o QR Code
        qr = qrcode.make(pix)
        buffer = BytesIO()
        qr.save(buffer, format="PNG")

        # Salvar o QR Code no banco de dados como imagem
        self.qr_code.save(f'qr_{self.codigo}.png',
                          ContentFile(buffer.getvalue()), save=False)

        return pix

    def save(self, *args, **kwargs):
        if self.valor is None:
            self.valor = 0
        if self.quantidade is None:
            self.quantidade = 0
        if self.codigo is '':
            self.codigo = self.gerar_codigo_unico()
        if self.valor is not None and self.quantidade is not None:

            self.valor_total = self.valor * self.quantidade
        else:
            self.valor_total = 0

        return super().save(*args, **kwargs)

    def __str__(self):
        return self.codigo


class HistoricoPedido(models.Model):
    pedido = models.ForeignKey(
        Pedido, on_delete=models.CASCADE, related_name="historico")
    alteracoes = models.JSONField()  # Guarda as mudanças feitas
    data_alteracao = models.DateTimeField(default=now)

empresa/views/carrossel_views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, redirect, get_object_or_404
from ..models import Empresa, FotosCarrossel
from ..forms import FotosCarrosselForm
import locale
locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')


def CarrosselProfileView(request):
    dados = Empresa.objects.get(pk=1)
    fotos = dados.fotos_carrossel.all()
    form = FotosCarrosselForm(initial={'empresa': dados})
    return render(request, 'empresa/profile-carrosel.html', {'dados': dados, 'form': form, 'fotos': fotos})


def DelFotoCarroselView(request, pk):
    foto = get_object_or_404(FotosCarrossel, pk=pk)
    foto.delete()
    return redirect('adm:carrossel')



def AddFotoCarroselView(request):
    if request.method == "POST":
        form = FotosCarrosselForm(request.POST or None,
                                  request.FILES or None,)
        if form.is_valid():
            form.save()
            print('salvo')
            return redirect('adm:carrossel')
        else:
            print(form.errors) 
            return redirect('adm:carrossel')
    return redirect('adm:carrossel')

empresa/views/pedidos_views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from ..models import Empresa, Pedido
from ..forms import PedidosForm, ProcurarForm, ClienteForm
import locale
locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')


def PedidosListView(request):
    pesquisa = request.GET.get('q', '').strip()
    pg = request.GET.get('pago', '').strip()
    status = request.GET.get('status', '').strip()
    filtro_q = Q()
    filtro_pg = Q()
    filtro_est = Q()
    if pesquisa:
        filtro_q = Q(codigo__icontains=pesquisa) | Q(
            cliente__nome__icontains=pesquisa)
    if pg in ["True", "False"]:  
        filtro_pg = Q(pago=(pg))
    if status:
        filtro_est = Q(status=status)
    dados = Empresa.objects.get(pk=1)
    pedidos = Pedido.objects.filter(
        filtro_q & filtro_pg & filtro_est).order_by('status', '-id')
    form = ProcurarForm(request.GET or None)
    return render(request, 'empresa/profile-pedidos.html', {'form': form, 'dados': dados, 'pedidos': pedidos, })

def PedidodetailView(request, pk):
    dados = Empresa.objects.get(pk=1)
    pedido = Pedido.objects.get(pk=pk)
    form = PedidosForm(instance=pedido)
    return render(request, 'empresa/pedido-detail.html', {'dados': dados, 'pedido': pedido, 'form': form, })

def PedidoEditView(request, pk):
    pedido = get_object_or_404(Pedido, pk=pk)
    if request.method == "POST":
        form = PedidosForm(request.POST or None, instance=pedido)
        if form.is_valid():
            form.save()
            return redirect('adm:fechar_pagina')
        else:
            print(form.errors)  
            return redirect('adm:pedidos')
    return redirect('adm:pedidos')


def PedidoDelView(request, pk):
    pedido = get_object_or_404(Pedido, pk=pk)
    if request.method == "POST":
        pedido.delete()
        return redirect('adm:fechar_pagina')
    return redirect('adm:pedidos')


def PedidoNewView(request):
    dados = Empresa.objects.get(pk=1)
    form = PedidosForm()
    formcliente = ClienteForm()
    if request.method == 'POST':
        formcliente = ClienteForm(request.POST)
        if formcliente.is_valid():  
            formcliente.save()
    return render(request, 'empresa/pedido-new.html', {'dados': dados, 'form': form, 'formcliente':formcliente})


def PedidoNewSaveView(request):
    form = PedidosForm()
    if request.method == "POST":
        if request.method == 'POST':
            form = PedidosForm(request.POST)
            if form.is_valid():  
                pedido = form.save(commit=False)
                pedido.save()
                return redirect('adm:fechar_pagina')
            else:
                return render(request, 'empresa/pedido-new.html', {'form': form})

joycebordados/views.py
from django.shortcuts import render, redirect
from empresa.models import Empresa
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def HomeView(request):
    dados = Empresa.objects.get(pk=1)
    fotos = dados.fotos_carrossel.all() if dados else []
    return render(request, 'joycebordados/index.html', context={'dados': dados, 'fotos': fotos, })

def red(request, cod):
    return redirect(f'/cliente/pedido/?codigo={cod}')

joycebordados/templates/joycebordados/partial/carrossel.html
{% load static %}
<div class="swiper">
  <!-- Additional required wrapper -->
  <div class="swiper-wrapper">
    <!-- Slides -->
    {% for foto in fotos %}
    <div class="swiper-slide">
     <img src="{{ foto.foto.url }}" alt="" />
    </div>
    {% endfor %}
  </div>
  <!-- If we need pagination -->
  <div class="swiper-pagination"></div>

  <!-- If we need navigation buttons -->
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>

  <!-- If we need scrollbar -->
  <div class="swiper-scrollbar"></div>
</div>

<script src="{% static 'global/js/carrossel.js' %}"></script>

joycebordados/templates/joycebordados/partial/google.html
{% load filtros %}
<div class="conteiner">
<div class="google-conteiner " id="contato">
  <div class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1986.9497658272242!2d-42.80906013855407!3d-5.11988943484389!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x78e37001ecd5bb9%3A0x7e997b96627a021!2sJoyce%20Bordados!5e0!3m2!1spt-BR!2sbr!4v1741400911774!5m2!1spt-BR!2sbr" width="600" height="450" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
  </div>
  <div class="localizacao">
    <h2>Localização</h2>
    <p>{{ dados.endereco }}</p>
    <p>{{ dados.cidade }} - {{ dados.estado }}</p>
    <p>{{ dados.bairro }}</p>
    <p>CEP: {{ dados.cep }}</p>
  </div>
  <div class="contato">
    <h2>Contato</h2>
    <p>Telefone: {{ dados.telefone|formatar_telefone }}</p>
    <p>Email: {{ dados.email }}</p>
    <a href="https://api.whatsapp.com/send?phone=55{{ dados.telefone }}&text=*Ol%C3%A1%2C%20gostaria%20de%20um%20or%C3%A7amento*.%0APode%20me%C2%A0ajudar%3F" target="_blank"><button class='gren'>Whatsapp</button></a>
  </div>
</div>
</div>

joycebordados/templates/joycebordados/partial/orcamento.html
<div class="conteiner">
    <div class="orcamento-container">
    <div class="orcamento-text ">
        <h2>Orçamento</h2>
        <p>Entre em contato conosco para solicitar um orçamento.</p>
    </div>
    <div class="orcamento-form">
        <form action="{% url 'cliente:orcamento' %}" method="post">
            {% csrf_token %}
            <input class="input-style" type="text" name="nome" placeholder="Nome" required>
            <input class="input-style" type="email" name="email" placeholder="Email">
            <input class="input-style" type="text" name="telefone" placeholder="Telefone">
            <textarea class="input-style" name="mensagem" placeholder="Mensagem" required style="resize: none;"></textarea>
            <button type="submit">Enviar</button>
        </form>
    </div>
</div>
</div>

joycebordados/templates/joycebordados/partial/pedido.html
{% load filtros %}

<div
  class="pedido-conteiner {% if pedido.status.0 == '1' %} red {% elif pedido.status.0 == '2' %} gren {% elif pedido.status.0 == '3' %} gray {% endif %}"
>
  <div class="cliente">
    <h2>Cliente</h2>
    <a href="{% url 'adm:detail-pedido' pk=pedido.pk %}"
      ><button type="button">Detalhe</button></a
    >
    <p><strong>Nome:</strong> {{ pedido.cliente.nome }}</p>
    <p>
      <strong>Telefone:</strong> {{ pedido.cliente.numero|formatar_telefone }}
    </p>
  </div>
  <hr />
  <div class="pedido">
    <h2>Pedido</h2>
    {% if pedido.pago %}<span class="icon yes">✅</span>{% else %}<span
      class="icon no"
      >❌</span
    >{% endif %}
    <p class="cod-pedido">
      <strong>#{{ pedido.codigo }}</strong>
    </p>
    <p>
      <strong>Data de Entrega:</strong>
      {{ pedido.data_entrega|date:'d/m/Y' }}
    </p>
    <p>
      <strong>{{ pedido.produto }}</strong>
    </p>
    <p>
      <strong>Descrição:</strong>
      {{ pedido.observacao }}
    </p>
    <p>
      <strong>Status:</strong>
      {{ pedido.get_status_display }}
    </p>
  </div>
</div>

joycebordados/templates/joycebordados/partial/servicos.html
<div class="conteiner">
    <div class="servicos-conteiner " id="servicos">
    <div class="serv bordado">
        <h2>Bordado</h2>
        <p>Trabalhamos com bordados computadorizados, que garantem qualidade e precisão nos detalhes. Bordamos em camisetas, uniformes, toalhas, bonés, entre outros.</p>
    </div>
    <div class="serv camisaeventos">
        <h2>Camisas para Eventos</h2>
        <p>Camisas personalizadas para eventos, festas, formaturas, entre outros. Trabalhamos com estampas e bordados, garantindo qualidade e durabilidade.</p>
    </div>
</div>
</div>

joycebordados/templates/joycebordados/partial/sobre.html
{% load static %}
<div class="conteiner">
  <div class="sobre-conteiner ">
  <div class="sobre">
    <h2>Sobre nós</h2>
    <p>A Joyce Bordados é uma empresa especializada em bordados computadorizados e confecção de uniformes. Trabalhamos com bordados em camisetas, toalhas, bonés, entre outros. Confeccionamos fardamentos para empresas, escolas, eventos, entre outros. Trabalhamos com uniformes personalizados, com bordados e estampas. Além disso, produzimos camisas personalizadas para eventos, festas, formaturas, entre outros. Trabalhamos com estampas e bordados, garantindo qualidade e durabilidade.</p>
  </div>
  <div class="sobre-img">
    <img src="{{ dados.foto_sobre.url }}" alt="" />
  </div>
</div>
</div>